name: Terraform Apply to GCP

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # no es obligatorio con SA key, pero útil si luego migrás a WIF

    env:
      TF_IN_AUTOMATION: true
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id:  ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region:      ${{ secrets.GCP_REGION }}
      TF_VAR_zone:        ${{ secrets.GCP_ZONE }}
      # TF_VAR_service_account_email: "gh-terraform-sa@<PROYECTO>.iam.gserviceaccount.com" # opcional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # (Opcional) Valida formato
      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      # ⚠️ Para aplicar cambios automáticamente al hacer push a main:
      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
